# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tp-home008/vblum/Documents/TI/tp1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tp-home008/vblum/Documents/TI/tp1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tp-home008/vblum/Documents/TI/tp1/CMakeFiles /home/tp-home008/vblum/Documents/TI/tp1/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tp-home008/vblum/Documents/TI/tp1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named result

# Build rule for target.
result: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 result
.PHONY : result

# fast build rule for target.
result/fast:
	$(MAKE) -f CMakeFiles/result.dir/build.make CMakeFiles/result.dir/build
.PHONY : result/fast

#=============================================================================
# Target rules for targets named lectureImage

# Build rule for target.
lectureImage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lectureImage
.PHONY : lectureImage

# fast build rule for target.
lectureImage/fast:
	$(MAKE) -f CMakeFiles/lectureImage.dir/build.make CMakeFiles/lectureImage.dir/build
.PHONY : lectureImage/fast

#=============================================================================
# Target rules for targets named seuilGris

# Build rule for target.
seuilGris: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 seuilGris
.PHONY : seuilGris

# fast build rule for target.
seuilGris/fast:
	$(MAKE) -f CMakeFiles/seuilGris.dir/build.make CMakeFiles/seuilGris.dir/build
.PHONY : seuilGris/fast

#=============================================================================
# Target rules for targets named sobel

# Build rule for target.
sobel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sobel
.PHONY : sobel

# fast build rule for target.
sobel/fast:
	$(MAKE) -f CMakeFiles/sobel.dir/build.make CMakeFiles/sobel.dir/build
.PHONY : sobel/fast

#=============================================================================
# Target rules for targets named evaluation

# Build rule for target.
evaluation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 evaluation
.PHONY : evaluation

# fast build rule for target.
evaluation/fast:
	$(MAKE) -f CMakeFiles/evaluation.dir/build.make CMakeFiles/evaluation.dir/build
.PHONY : evaluation/fast

evaluation.o: evaluation.cpp.o

.PHONY : evaluation.o

# target to build an object file
evaluation.cpp.o:
	$(MAKE) -f CMakeFiles/evaluation.dir/build.make CMakeFiles/evaluation.dir/evaluation.cpp.o
.PHONY : evaluation.cpp.o

evaluation.i: evaluation.cpp.i

.PHONY : evaluation.i

# target to preprocess a source file
evaluation.cpp.i:
	$(MAKE) -f CMakeFiles/evaluation.dir/build.make CMakeFiles/evaluation.dir/evaluation.cpp.i
.PHONY : evaluation.cpp.i

evaluation.s: evaluation.cpp.s

.PHONY : evaluation.s

# target to generate assembly for a file
evaluation.cpp.s:
	$(MAKE) -f CMakeFiles/evaluation.dir/build.make CMakeFiles/evaluation.dir/evaluation.cpp.s
.PHONY : evaluation.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/lectureImage.dir/build.make CMakeFiles/lectureImage.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/lectureImage.dir/build.make CMakeFiles/lectureImage.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/lectureImage.dir/build.make CMakeFiles/lectureImage.dir/main.cpp.s
.PHONY : main.cpp.s

result.o: result.cpp.o

.PHONY : result.o

# target to build an object file
result.cpp.o:
	$(MAKE) -f CMakeFiles/result.dir/build.make CMakeFiles/result.dir/result.cpp.o
.PHONY : result.cpp.o

result.i: result.cpp.i

.PHONY : result.i

# target to preprocess a source file
result.cpp.i:
	$(MAKE) -f CMakeFiles/result.dir/build.make CMakeFiles/result.dir/result.cpp.i
.PHONY : result.cpp.i

result.s: result.cpp.s

.PHONY : result.s

# target to generate assembly for a file
result.cpp.s:
	$(MAKE) -f CMakeFiles/result.dir/build.make CMakeFiles/result.dir/result.cpp.s
.PHONY : result.cpp.s

seuilGris.o: seuilGris.cpp.o

.PHONY : seuilGris.o

# target to build an object file
seuilGris.cpp.o:
	$(MAKE) -f CMakeFiles/seuilGris.dir/build.make CMakeFiles/seuilGris.dir/seuilGris.cpp.o
.PHONY : seuilGris.cpp.o

seuilGris.i: seuilGris.cpp.i

.PHONY : seuilGris.i

# target to preprocess a source file
seuilGris.cpp.i:
	$(MAKE) -f CMakeFiles/seuilGris.dir/build.make CMakeFiles/seuilGris.dir/seuilGris.cpp.i
.PHONY : seuilGris.cpp.i

seuilGris.s: seuilGris.cpp.s

.PHONY : seuilGris.s

# target to generate assembly for a file
seuilGris.cpp.s:
	$(MAKE) -f CMakeFiles/seuilGris.dir/build.make CMakeFiles/seuilGris.dir/seuilGris.cpp.s
.PHONY : seuilGris.cpp.s

sobel.o: sobel.cpp.o

.PHONY : sobel.o

# target to build an object file
sobel.cpp.o:
	$(MAKE) -f CMakeFiles/sobel.dir/build.make CMakeFiles/sobel.dir/sobel.cpp.o
.PHONY : sobel.cpp.o

sobel.i: sobel.cpp.i

.PHONY : sobel.i

# target to preprocess a source file
sobel.cpp.i:
	$(MAKE) -f CMakeFiles/sobel.dir/build.make CMakeFiles/sobel.dir/sobel.cpp.i
.PHONY : sobel.cpp.i

sobel.s: sobel.cpp.s

.PHONY : sobel.s

# target to generate assembly for a file
sobel.cpp.s:
	$(MAKE) -f CMakeFiles/sobel.dir/build.make CMakeFiles/sobel.dir/sobel.cpp.s
.PHONY : sobel.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... result"
	@echo "... lectureImage"
	@echo "... seuilGris"
	@echo "... sobel"
	@echo "... evaluation"
	@echo "... evaluation.o"
	@echo "... evaluation.i"
	@echo "... evaluation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... result.o"
	@echo "... result.i"
	@echo "... result.s"
	@echo "... seuilGris.o"
	@echo "... seuilGris.i"
	@echo "... seuilGris.s"
	@echo "... sobel.o"
	@echo "... sobel.i"
	@echo "... sobel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

